{
	src
	{
		types-attributes.m
		general-group.m
		general-fusion-system.m
		properties-fusion-systems.m
		group-properties-fusion-system.m
		all-proto-essentials.m
		generating-fusion-systems.m
		saving-fusion-systems.m
		all-fusion-systems.m
	}
}