// AutOrbit
P := DirectProduct(CyclicGroup(2), CyclicGroup(2));
MakeAutos(P);
AFP := P`autogrp;  // Full automorphism group of P
Q := sub<P | P.1>; // Subgroup generated by the first factor
Orb, StB, Elt := AutOrbit(P, Q, AFP : Printing := true);
Orb,StB,Elt;
// Check expected properties
assert #Orb eq 3;  // Aut(C2×C2) acts transitively on 3 nontrivial subgroups
assert forall{H : H in Orb | #H eq #Q};  // Orbit members are same order
assert forall{a : a in Generators(StB) | a(Q) eq Q};  // Stabilizer fixes Q
print "AutOrbit (subgroup version) test passed.";

// Legacy output
/*
[
    Permutation group acting on a set of cardinality 4
    Order = 2
        (1, 2),
    Permutation group acting on a set of cardinality 4
    Order = 2
        (3, 4),
    Permutation group acting on a set of cardinality 4
    Order = 2
        (1, 2)(3, 4)
]
A group of automorphisms of GrpPerm: P, Degree 4, Order 2^2
Generators:
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 which maps:
        (1, 2) |--> (1, 2)
        (3, 4) |--> (3, 4)
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 which maps:
        (1, 2) |--> (1, 2)
        (3, 4) |--> (1, 2)(3, 4)
[
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 of order 1 which maps:
        (1, 2) |--> (1, 2)
        (3, 4) |--> (3, 4),
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 of order 3 which maps:
        (1, 2) |--> (3, 4)
        (3, 4) |--> (1, 2)(3, 4),
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 of order 2 which maps:
        (1, 2) |--> (1, 2)(3, 4)
        (3, 4) |--> (3, 4)
]
*/


// Element version
x := P.1; // Choose an element of order 2
Orb, NN, Elt := AutOrbit(P, x, AFP);
Orb, NN, Elt;
// The orbit should contain all 3 nonidentity elements of order 2
assert #Orb eq 3;
assert forall{y : y in Orb | Order(y) eq Order(x)};
assert forall{phi : phi in Generators(NN) | phi(x) eq x};  // Stabilizer fixes x
print "AutOrbit (element version) test passed.";

// Legacy output
/*
[
    (1, 2),
    (3, 4),
    (1, 2)(3, 4)
]
A group of automorphisms of GrpPerm: P, Degree 4, Order 2^2
Generators:
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 which maps:
        (1, 2) |--> (1, 2)
        (3, 4) |--> (1, 2)(3, 4)
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 which maps:
        (1, 2) |--> (1, 2)
        (3, 4) |--> (1, 2)(3, 4)
[
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 of order 1 which maps:
        (1, 2) |--> (1, 2)
        (3, 4) |--> (3, 4),
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 of order 2 which maps:
        (1, 2) |--> (3, 4)
        (3, 4) |--> (1, 2),
    Automorphism of GrpPerm: P, Degree 4, Order 2^2 which maps:
        (1, 2) |--> (1, 2)(3, 4)
        (3, 4) |--> (3, 4)
]
*/